name: GoReleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create bin dir
        run: | 
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Download pkl-lang
        run: | 
          curl -L -o pkl https://github.com/apple/pkl/releases/download/0.26.1/pkl-linux-amd64
          chmod +x pkl
          cp pkl $HOME/.local/bin/
      - name: Download hpkl
        run:  |
          curl -L -o hpkl.tar.gz https://github.com/hpklio/hpkl/releases/download/v0.2.0/hpkl_Linux_x86_64.tar.gz
          tar -xzvf hpkl.tar.gz
          chmod +x hpkl
          cp hpkl $HOME/.local/bin/
      - name: Build & Publish
        run: |
          hpkl resolve
          hpkl package
          hpkl login -l ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          hpkl publish
